#include "celestial/star_catalog.hpp"

#include <algorithm>
#include <cmath>
#include <unordered_map>

// ---------------------------------------------------------------------------
// star_names.cpp — common names for the brightest BSC5 entries.
//
// GENERATED by matching J2000 positions against the catalogue and verifying
// against magnitude, rather than trusting remembered HR numbers. That check
// caught one mislabelled star (Avior had been given Naos\'s right ascension)
// and flagged two binaries where BSC5 lists the components separately
// (alpha Centauri, Castor), which are matched on position alone.
//
// Only the ~65 navigational stars are named; everything else falls back to
// "HR nnnn", which is what you want on a plot anyway.
// ---------------------------------------------------------------------------

namespace celestial {
namespace {

std::vector<CatalogStar> buildCatalog() {
  std::vector<CatalogStar> out;
  out.reserve(detail::kBsc5Count);
  for (int i = 0; i < detail::kBsc5Count; ++i) {
    const detail::CatalogRaw& r = detail::kBsc5[i];
    CatalogStar s;
    s.id = r.hr;
    s.ra = r.ra_deg * kDeg2Rad;
    s.dec = r.dec_deg * kDeg2Rad;
    // The generator emits dRA/dt directly, which is what ERFA wants; no
    // cos(dec) division here (unlike a Hipparcos mu_alpha* table).
    s.pm_ra_star = r.pm_ra_arcsec * kArcsec2Rad;
    s.pm_dec = r.pm_dec_arcsec * kArcsec2Rad;
    s.vmag = r.vmag;
    out.push_back(s);
  }
  return out;
}

}  // namespace

const std::vector<CatalogStar>& brightStarCatalog() {
  static const std::vector<CatalogStar> kCatalog = buildCatalog();
  return kCatalog;
}

std::vector<CatalogStar> catalogBrighterThan(double vmag_limit) {
  const auto& all = brightStarCatalog();
  std::vector<CatalogStar> out;
  for (const CatalogStar& s : all) {
    if (s.vmag > vmag_limit) break;  // sorted by magnitude
    out.push_back(s);
  }
  return out;
}

const CatalogStar* findStar(int id) {
  static const std::unordered_map<int, const CatalogStar*> kIndex = [] {
    std::unordered_map<int, const CatalogStar*> m;
    for (const CatalogStar& s : brightStarCatalog()) m[s.id] = &s;
    return m;
  }();
  auto it = kIndex.find(id);
  return it == kIndex.end() ? nullptr : it->second;
}


namespace {
struct Named { int hr; const char* name; };
const Named kNames[] = {
    {15, "Alpheratz"},
    {21, "Caph"},
    {188, "Diphda"},
    {424, "Polaris"},
    {472, "Achernar"},
    {617, "Hamal"},
    {936, "Algol"},
    {1017, "Mirfak"},
    {1457, "Aldebaran"},
    {1708, "Capella"},
    {1713, "Rigel"},
    {1790, "Bellatrix"},
    {1791, "Elnath"},
    {1852, "Mintaka"},
    {1903, "Alnilam"},
    {1948, "Alnitak"},
    {2004, "Saiph"},
    {2061, "Betelgeuse"},
    {2088, "Menkalinan"},
    {2294, "Mirzam"},
    {2326, "Canopus"},
    {2421, "Alhena"},
    {2491, "Sirius"},
    {2618, "Adhara"},
    {2693, "Wezen"},
    {2891, "Castor"},
    {2943, "Procyon"},
    {2990, "Pollux"},
    {3165, "Naos"},
    {3307, "Avior"},
    {3634, "Suhail"},
    {3685, "Miaplacidus"},
    {3748, "Alphard"},
    {3982, "Regulus"},
    {4301, "Dubhe"},
    {4534, "Denebola"},
    {4730, "Acrux"},
    {4763, "Gacrux"},
    {4853, "Mimosa"},
    {4905, "Alioth"},
    {5054, "Mizar"},
    {5056, "Spica"},
    {5191, "Alkaid"},
    {5267, "Hadar"},
    {5288, "Menkent"},
    {5340, "Arcturus"},
    {5460, "Rigil Kent"},
    {5563, "Kochab"},
    {6134, "Antares"},
    {6217, "Atria"},
    {6527, "Shaula"},
    {6553, "Sargas"},
    {6556, "Rasalhague"},
    {6705, "Eltanin"},
    {7001, "Vega"},
    {7121, "Nunki"},
    {7557, "Altair"},
    {7790, "Peacock"},
    {7796, "Sadr"},
    {7924, "Deneb"},
    {8162, "Alderamin"},
    {8308, "Enif"},
    {8425, "Alnair"},
    {8728, "Fomalhaut"},
    {8775, "Scheat"},
    {8781, "Markab"},
};
}  // namespace

const char* starName(int id) {
  static const std::unordered_map<int, const char*> kMap = [] {
    std::unordered_map<int, const char*> m;
    for (const Named& n : kNames) m[n.hr] = n.name;
    return m;
  }();
  auto it = kMap.find(id);
  return it == kMap.end() ? nullptr : it->second;
}

}  // namespace celestial
