#!/usr/bin/env python3
"""Regenerate src/star_catalog_data.cpp from the Yale Bright Star Catalogue.

    curl -L -o BSC.json \
      https://raw.githubusercontent.com/aduboisforge/Bright-Star-Catalog-JSON/master/BSC.json
    python3 tools/analysis/make_catalog.py BSC.json 6.0 > src/star_catalog_data.cpp

Deeper catalogues cost compile time and memory but let you simulate a more
sensitive detector. V=6.0 gives 5080 stars, which yields roughly 230 stars in a
53.5 x 35.1 deg field -- more than any realistic detector will find, so set the
detection limit in ErrorModel::mag_limit rather than by truncating here.
"""
import json, sys

path = sys.argv[1]
limit = float(sys.argv[2]) if len(sys.argv) > 2 else 6.0
rows = []
for e in json.load(open(path)):
    ra, dec, mag = e.get('RA', '').strip(), e.get('DEC', '').strip(), e.get('MAG', '').strip()
    if not ra or not dec or not mag:
        continue
    try:
        h, m, s = [float(x) for x in ra.split(':')]
        dp = dec.replace('+', '').split(':')
        sign = -1.0 if dec.startswith('-') else 1.0
        v = float(mag)
        pmra = float(e.get('RA PM', '0') or 0)
        pmdec = float(e.get('DEC PM', '0') or 0)
    except Exception:
        continue
    if v > limit:
        continue
    rows.append((int(e['harvard_ref_#']), (h + m / 60 + s / 3600) * 15,
                 sign * (abs(float(dp[0])) + float(dp[1]) / 60 + float(dp[2]) / 3600),
                 pmra * 15.0, pmdec, v))
rows.sort(key=lambda r: r[5])
print('// GENERATED by tools/analysis/make_catalog.py -- do not edit by hand.')
print('#include "celestial/star_catalog.hpp"')
print('namespace celestial {\nnamespace detail {\nconst CatalogRaw kBsc5[] = {')
for r in rows:
    print('{%d,%.6f,%.6f,%.5f,%.5f,%.2f},' % r)
print('};\nconst int kBsc5Count = %d;\n}  // namespace detail\n}  // namespace celestial' % len(rows))
